{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-forcats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/forcats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forcats/forcats_{{ version }}.tar.gz
  sha256: 8f960e789333ec597ddf2d653a64e330f03b86f465e9b71f6779f227355d90c4

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ellipsis
    - r-magrittr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-ellipsis
    - r-magrittr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('forcats')"           # [not win]
    - "\"%R%\" -e \"library('forcats')\""  # [win]

about:
  home: http://forcats.tidyverse.org, https://github.com/tidyverse/forcats
  license: GPL-3
  summary: Helpers for reordering factor levels (including moving specified levels to front, ordering by first appearance, reversing, and randomly shuffling), and
    tools for modifying factor levels (including collapsing rare levels into other, 'anonymising', and manually 'recoding').
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: forcats
# Title: Tools for Working with Categorical Variables (Factors)
# Version: 0.4.0
# Authors@R:  c(person(given = "Hadley", family = "Wickham", role = c("aut", "cre"), email = "hadley@rstudio.com"), person(given = "RStudio", role = c("cph", "fnd")))
# Description: Helpers for reordering factor levels (including moving specified levels to front, ordering by first appearance, reversing, and randomly shuffling), and tools for modifying factor levels (including collapsing rare levels into other, 'anonymising', and manually 'recoding').
# License: GPL-3
# URL: http://forcats.tidyverse.org, https://github.com/tidyverse/forcats
# BugReports: https://github.com/tidyverse/forcats/issues
# Depends: R (>= 3.1)
# Imports: ellipsis, magrittr, rlang, tibble
# Suggests: covr, ggplot2, testthat, readr, knitr, rmarkdown, dplyr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-02-17 14:15:34 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-02-17 14:40:02 UTC
