{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-forcats
  version: {{ version|replace("-", "_") }}

source:
  fn: forcats_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/forcats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forcats/forcats_{{ version }}.tar.gz
  sha256: 7c83cb576aa6fe1379d7506dcc332f7560068b2025f9e3ab5cd0a5f28780d2b2

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-magrittr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-magrittr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('forcats')"           # [not win]
    - "\"%R%\" -e \"library('forcats')\""  # [win]

about:
  home: http://forcats.tidyverse.org, https://github.com/tidyverse/forcats
  license: GPL-3
  summary: Helpers for reordering factor levels (including moving specified levels to front,
    ordering by first appearance, reversing, and randomly shuffling), and tools for
    modifying factor levels (including collapsing rare levels into other, 'anonymising',
    and manually 'recoding').
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
