{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-forcats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/forcats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forcats/forcats_{{ version }}.tar.gz
  sha256: 1de46b83b7038a293e612775197b7ffe47bd079cd2385aa7c65e98171bbd3605

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cli
    - r-ellipsis
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-rlang >=1.0.0
    - r-tibble
    - r-withr
  run:
    - r-base
    - r-cli
    - r-ellipsis
    - r-glue
    - r-lifecycle
    - r-magrittr
    - r-rlang >=1.0.0
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('forcats')"           # [not win]
    - "\"%R%\" -e \"library('forcats')\""  # [win]

about:
  home: http://forcats.tidyverse.org, https://github.com/tidyverse/forcats
  license: MIT
  summary: Helpers for reordering factor levels (including moving specified levels to front, ordering by first appearance, reversing, and randomly shuffling), and tools for modifying factor levels (including collapsing rare levels into other, 'anonymising', and manually 'recoding').
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
