# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rg+Ie38ewcrD5J7+dzd3UjmYdvD/DU+i/5U2znATbLTXiP+nWNwRXFIe3pNLfx4rXYUvPFzzhuYfems+FjMTeUlGrcbkh8cfd2oQ+jKJQQYSbwBOW8eQ3vewnTvf53/VY9DsW4Dk+qyZvMoUbXjaxfXKunqQIiQUvsdnbdhmGAfhYox+r5U3SNRoklr1vSMjmRCKsaW/e3ux8GC7m1UA2XvxV954eMvvqToME6YYmswLHnVJQqVsf3YquYiQhUeXX8c/rmdhmAv/iqw2J0vOglYtX8tey5RV3niMF1MFiM3tANqjlYkYqHH+ZVMYjly+yQKPUHL73N2Jus8uWoVpBaTaamvZT9fqQhep63Ahf9HtcOKoa2VMSZh5eZv2OR6ZMxdBbWnxOhXuqV/ugwUWWmY0sBfhANrzIK5AhalhZf8s+YvBCqdJs6QsMztgInv2dFFJ8JAdOPsoUSGJF+7PLmf/GYdb4vAmCKWcI/l1FyhbaYfCtash3m5XTKjdA5sM0dI3KPuK820JiRbdty5LmtVXAi6iI0IulWDrGNcMmmM8uPhD1uMluIljXQ9mBgnbFzeXl0QMbyhLuaUxoDMaIW8y5tScg5Mndx4z4TgSvV+f1ObmW+mCS42cWimuC0ngUthOm9MU1+IsV+wf8dYkzi6ek3vcw7Z5ruGjzNGRoAA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
