appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: rg+Ie38ewcrD5J7+dzd3UjmYdvD/DU+i/5U2znATbLTXiP+nWNwRXFIe3pNLfx4rXYUvPFzzhuYfems+FjMTeUlGrcbkh8cfd2oQ+jKJQQYSbwBOW8eQ3vewnTvf53/VY9DsW4Dk+qyZvMoUbXjaxfXKunqQIiQUvsdnbdhmGAfhYox+r5U3SNRoklr1vSMjmRCKsaW/e3ux8GC7m1UA2XvxV954eMvvqToME6YYmswLHnVJQqVsf3YquYiQhUeXX8c/rmdhmAv/iqw2J0vOglYtX8tey5RV3niMF1MFiM3tANqjlYkYqHH+ZVMYjly+yQKPUHL73N2Jus8uWoVpBaTaamvZT9fqQhep63Ahf9HtcOKoa2VMSZh5eZv2OR6ZMxdBbWnxOhXuqV/ugwUWWmY0sBfhANrzIK5AhalhZf8s+YvBCqdJs6QsMztgInv2dFFJ8JAdOPsoUSGJF+7PLmf/GYdb4vAmCKWcI/l1FyhbaYfCtash3m5XTKjdA5sM0dI3KPuK820JiRbdty5LmtVXAi6iI0IulWDrGNcMmmM8uPhD1uMluIljXQ9mBgnbFzeXl0QMbyhLuaUxoDMaIW8y5tScg5Mndx4z4TgSvV+f1ObmW+mCS42cWimuC0ngUthOm9MU1+IsV+wf8dYkzi6ek3vcw7Z5ruGjzNGRoAA=}
bot:
  automerge: true
